SEED_PRODUCTS = [
    # ── Fruits & Vegetables ─────────────────────────────────────────────
    {
        "name": "Banana - Robusta",
        "description": "Fresh bananas, rich in potassium",
        "price": 39.0,
        "mrp": 49.0,
        "category": "Fruits & Vegetables",
        "sub_category": "Fresh Fruits",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/banana.jpg",
        "unit": "1 dozen",
        "in_stock": True,
        "stock_qty": 200,
    },
    {
        "name": "Tomato - Local",
        "description": "Farm-fresh red tomatoes",
        "price": 29.0,
        "mrp": 35.0,
        "category": "Fruits & Vegetables",
        "sub_category": "Fresh Vegetables",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/tomato.jpg",
        "unit": "500 g",
        "in_stock": True,
        "stock_qty": 300,
    },
    {
        "name": "Onion",
        "description": "Premium quality onions",
        "price": 35.0,
        "mrp": 45.0,
        "category": "Fruits & Vegetables",
        "sub_category": "Fresh Vegetables",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/onion.jpg",
        "unit": "1 kg",
        "in_stock": True,
        "stock_qty": 250,
    },
    {
        "name": "Apple - Shimla",
        "description": "Crisp Shimla apples",
        "price": 149.0,
        "mrp": 180.0,
        "category": "Fruits & Vegetables",
        "sub_category": "Fresh Fruits",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/apple.jpg",
        "unit": "1 kg",
        "in_stock": True,
        "stock_qty": 100,
    },
    # ── Dairy & Breakfast ───────────────────────────────────────────────
    {
        "name": "Amul Toned Milk",
        "description": "Pasteurised toned milk",
        "price": 29.0,
        "mrp": 30.0,
        "category": "Dairy & Breakfast",
        "sub_category": "Milk",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/amul_milk.jpg",
        "unit": "500 ml",
        "in_stock": True,
        "stock_qty": 400,
    },
    {
        "name": "Amul Butter",
        "description": "Pasteurised butter",
        "price": 56.0,
        "mrp": 57.0,
        "category": "Dairy & Breakfast",
        "sub_category": "Butter & Cheese",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/amul_butter.jpg",
        "unit": "100 g",
        "in_stock": True,
        "stock_qty": 150,
    },
    {
        "name": "Britannia Brown Bread",
        "description": "Whole wheat brown bread",
        "price": 45.0,
        "mrp": 50.0,
        "category": "Dairy & Breakfast",
        "sub_category": "Bread",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/bread.jpg",
        "unit": "400 g",
        "in_stock": True,
        "stock_qty": 120,
    },
    {
        "name": "Amul Paneer",
        "description": "Fresh malai paneer",
        "price": 85.0,
        "mrp": 90.0,
        "category": "Dairy & Breakfast",
        "sub_category": "Paneer & Tofu",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/paneer.jpg",
        "unit": "200 g",
        "in_stock": True,
        "stock_qty": 80,
    },
    # ── Snacks & Munchies ───────────────────────────────────────────────
    {
        "name": "Lays Classic Salted",
        "description": "Crispy potato chips",
        "price": 20.0,
        "mrp": 20.0,
        "category": "Snacks & Munchies",
        "sub_category": "Chips & Crisps",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/lays.jpg",
        "unit": "52 g",
        "in_stock": True,
        "stock_qty": 500,
    },
    {
        "name": "Kurkure Masala Munch",
        "description": "Crunchy puffed corn snack",
        "price": 20.0,
        "mrp": 20.0,
        "category": "Snacks & Munchies",
        "sub_category": "Namkeen",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/kurkure.jpg",
        "unit": "75 g",
        "in_stock": True,
        "stock_qty": 350,
    },
    # ── Beverages ───────────────────────────────────────────────────────
    {
        "name": "Coca-Cola",
        "description": "Refreshing cola drink",
        "price": 40.0,
        "mrp": 40.0,
        "category": "Beverages",
        "sub_category": "Soft Drinks",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/coke.jpg",
        "unit": "750 ml",
        "in_stock": True,
        "stock_qty": 300,
    },
    {
        "name": "Tata Tea Gold",
        "description": "Premium leaf tea",
        "price": 150.0,
        "mrp": 165.0,
        "category": "Beverages",
        "sub_category": "Tea",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/tata_tea.jpg",
        "unit": "250 g",
        "in_stock": True,
        "stock_qty": 180,
    },
    # ── Cleaning & Household ────────────────────────────────────────────
    {
        "name": "Vim Dishwash Bar",
        "description": "Lemon fresh dishwash bar",
        "price": 10.0,
        "mrp": 10.0,
        "category": "Cleaning & Household",
        "sub_category": "Dishwash",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/vim.jpg",
        "unit": "130 g",
        "in_stock": True,
        "stock_qty": 400,
    },
    {
        "name": "Surf Excel Easy Wash",
        "description": "Detergent powder",
        "price": 120.0,
        "mrp": 135.0,
        "category": "Cleaning & Household",
        "sub_category": "Detergent",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/surf.jpg",
        "unit": "1 kg",
        "in_stock": True,
        "stock_qty": 160,
    },
    # ── Instant & Frozen Food ───────────────────────────────────────────
    {
        "name": "Maggi 2-Minute Noodles",
        "description": "Masala instant noodles",
        "price": 14.0,
        "mrp": 14.0,
        "category": "Instant & Frozen Food",
        "sub_category": "Noodles",
        "image_url": "https://cdn.grofers.com/app/images/products/sliding_images/jpeg/maggi.jpg",
        "unit": "70 g",
        "in_stock": True,
        "stock_qty": 600,
    },
]
